name: xeus-cling
channels:
  - conda-forge
dependencies:
  - python=3.10
  - gcc_linux-*64=9.4.0
  - xeus-cling
  - armadillo
  - openblas
  - arpack
  - superlu
  - hdf5
  - jupyterlab-h5web
  - notebook=7.*